---
- name: Install Python MySQLdb
  yum: name=MySQL-python.x86_64 state=latest

#- name: users | update root password for all hosts
#  mysql_user: >
#    name=root
#    host={{ item }}
#    password={{ mysql_root_password|default('') }}
#    priv=*.*:ALL,GRANT
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost

- name: users | add root credentials
  template: >
    src=my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=0600
  notify:
    - mysql-restart

#- name: Create the Wordpress database
#  mysql_db:
#    db={{ db_name }} 
#    state=present

- name: Download WordPress
  command: "{{item}}"
  with_items:
    - echo "CREATE USER 'user'@'localhost' IDENTIFIED BY 'P@ssword1'" | mysql
    - echo "create database wordpressdb" | mysql
    - echo "GRANT ALL PRIVILEGES ON wordpressdb.* TO 'user'@'localhost'" | mysql 
     

